import { MigrationInterface, QueryRunner } from 'typeorm';

export class DearPeace1744544032734 implements MigrationInterface {
  name = 'DearPeace1744544032734';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE SCHEMA matrix');
    await queryRunner.query(
      `CREATE TYPE "matrix"."bridge_type_enum" AS ENUM('whatsapp')`,
    );
    await queryRunner.query(`CREATE TABLE "matrix"."bridge"
                                 (
                                     "port"     integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     "type"     "matrix"."bridge_type_enum"              NOT NULL,
                                     "userMxid" character varying,
                                     CONSTRAINT "PK_a67c600b51a1ec8fe5aef6b2868" PRIMARY KEY ("port")
                                 )`);
    await queryRunner.query(`CREATE TABLE "matrix"."user"
                                 (
                                     "mxid"     character varying NOT NULL,
                                     "password" character varying NOT NULL,
                                     CONSTRAINT "uq_user" UNIQUE ("mxid"),
                                     CONSTRAINT "PK_51934148571760083e7e1850715" PRIMARY KEY ("mxid")
                                 )`);
    await queryRunner.query(`ALTER TABLE "matrix"."bridge"
            ADD CONSTRAINT "FK_903a2e44f9950d8cf9735b8b329" FOREIGN KEY ("userMxid") REFERENCES "matrix"."user" ("mxid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "matrix"."bridge"
            DROP CONSTRAINT "FK_903a2e44f9950d8cf9735b8b329"`);
    await queryRunner.query(`DROP TABLE "matrix"."user"`);
    await queryRunner.query(`DROP TABLE "matrix"."bridge"`);
    await queryRunner.query(`DROP TYPE "matrix"."bridge_type_enum"`);
    await queryRunner.query('DROP SCHEMA matrix');
  }
}
