import { MigrationInterface, QueryRunner } from "typeorm";

export class PackQuestion1744542028062 implements MigrationInterface {
    name = 'PackQuestion1744542028062'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user" ("user_pk" SERIAL NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_638bac731294171648258260ff2" UNIQUE ("password"), CONSTRAINT "PK_77995dbb713f79934555ac633b0" PRIMARY KEY ("user_pk"))`);
        await queryRunner.query(`CREATE TYPE "public"."bridge_type_enum" AS ENUM('whatsapp')`);
        await queryRunner.query(`CREATE TABLE "bridge" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "type" "public"."bridge_type_enum" NOT NULL, "bridgePort" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "UQ_12fc81702ff28159a5f56032d8d" UNIQUE ("bridgePort"), CONSTRAINT "pk_bridge_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "bridge" ADD CONSTRAINT "FK_70b256ee4249c47a818e4751993" FOREIGN KEY ("userId") REFERENCES "user"("user_pk") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bridge" DROP CONSTRAINT "FK_70b256ee4249c47a818e4751993"`);
        await queryRunner.query(`DROP TABLE "bridge"`);
        await queryRunner.query(`DROP TYPE "public"."bridge_type_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
    }

}
